name = "smtp-form-handler"
main = "src/index.ts"
compatibility_date = "2024-06-24"

[[containers]]
name = "smtp-backend"
image = { dockerfile = "Dockerfile" }

[env.production.vars]
SERVER_PORT = "8080"

# Secrets should be set using wrangler CLI:
# wrangler secret put SMTP_HOST
# wrangler secret put SMTP_PORT
# wrangler secret put SMTP_USERNAME
# wrangler secret put SMTP_PASSWORD
# wrangler secret put RECIPIENT_EMAIL
# wrangler secret put API_KEY